### ISSUE TITLE
Undefined method with_locale

### ISSUE THREAD

**Issue by tegon** [globalize/globalize#265]
I'm trying to extend Gloablize Translation class (add relationships and other columns), and it works well, but sometimes i get this error on update_attributes:

``` ruby
undefined method `with_locale' for #<Class:0x007fe0ba7c0e28>
```

and i have to restart WEBrick to get this working again.

I don't know if i am doing this right, i have tried two ways:

``` ruby
class GameTranslation < ActiveRecord::Base
```

``` ruby
class Game
  class Translation < ActiveRecord::Base
```

I'm working with rails 3.2.12 and globalize3 0.3.0. I also have custom methods for accessors, like easy_globalize3_accessors.

I'm doing something wrong?

Framework Trace:

```
activerecord (3.2.12) lib/active_record/dynamic_matchers.rb:55:in `method_missing'
activerecord (3.2.12) lib/active_record/relation/delegation.rb:14:in `block in with_locale'
activerecord (3.2.12) lib/active_record/relation.rb:241:in `block in scoping'
activerecord (3.2.12) lib/active_record/scoping.rb:98:in `with_scope'
activerecord (3.2.12) lib/active_record/relation.rb:241:in `scoping'
activerecord (3.2.12) lib/active_record/relation/delegation.rb:14:in `with_locale'
activerecord (3.2.12) lib/active_record/associations/collection_proxy.rb:100:in `method_missing'
globalize3 (0.3.0) lib/globalize/active_record/act_macro.rb:77:in `find_or_initialize_by_locale'
globalize3 (0.3.0) lib/globalize/active_record/adapter.rb:42:in `block in save_translations!'
globalize3 (0.3.0) lib/globalize/active_record/adapter.rb:40:in `each'
globalize3 (0.3.0) lib/globalize/active_record/adapter.rb:40:in `save_translations!'
globalize3 (0.3.0) lib/globalize/active_record/instance_methods.rb:174:in `save_translations!'
activesupport (3.2.12) lib/active_support/callbacks.rb:409:in `_run__386880861509897305__update__3833848143045071548__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_update_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
activerecord (3.2.12) lib/active_record/callbacks.rb:272:in `update'
activerecord (3.2.12) lib/active_record/persistence.rb:348:in `create_or_update'
activerecord (3.2.12) lib/active_record/callbacks.rb:264:in `block in create_or_update'
activesupport (3.2.12) lib/active_support/callbacks.rb:414:in `_run__386880861509897305__save__3833848143045071548__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
activerecord (3.2.12) lib/active_record/callbacks.rb:264:in `create_or_update'
activerecord (3.2.12) lib/active_record/persistence.rb:84:in `save'
activerecord (3.2.12) lib/active_record/validations.rb:50:in `save'
activerecord (3.2.12) lib/active_record/attribute_methods/dirty.rb:22:in `save'
activerecord (3.2.12) lib/active_record/transactions.rb:259:in `block (2 levels) in save'
activerecord (3.2.12) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
activerecord (3.2.12) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
activerecord (3.2.12) lib/active_record/transactions.rb:208:in `transaction'
activerecord (3.2.12) lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
activerecord (3.2.12) lib/active_record/transactions.rb:259:in `block in save'
activerecord (3.2.12) lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
activerecord (3.2.12) lib/active_record/transactions.rb:258:in `save'
activerecord (3.2.12) lib/active_record/persistence.rb:217:in `block in update_attributes'
activerecord (3.2.12) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
activerecord (3.2.12) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
activerecord (3.2.12) lib/active_record/transactions.rb:208:in `transaction'
activerecord (3.2.12) lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
activerecord (3.2.12) lib/active_record/persistence.rb:215:in `update_attributes'
actionpack (3.2.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.12) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.12) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.12) lib/active_support/callbacks.rb:436:in `_run__3656053641613815772__process_action__3634258741246511212__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.12) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.12) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.12) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.12) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.12) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.12) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.12) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.12) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.12) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.12) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:601:in `call'
sass (3.2.10) lib/sass/plugin/rack.rb:54:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.12) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `_run__387685671940788932__call__3833848143045071548__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.12) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.12) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.12) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.12) lib/rails/rack/logger.rb:16:in `call'
quiet_assets (1.0.1) lib/quiet_assets.rb:20:in `call_with_quiet_assets'
actionpack (3.2.12) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.12) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.12) lib/rails/engine.rb:479:in `call'
railties (3.2.12) lib/rails/application.rb:223:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.12) lib/rails/rack/log_tailer.rb:17:in `call'
rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```
