### ISSUE TITLE
Globalize 4.0.1 does not work with Rails 4.1.1

### ISSUE THREAD

**Issue by vuvanly** [globalize/globalize#357]
Here is my model:

``` ruby
class Category < ActiveRecord::Base
  translates :name
end
```

I got this bug when using globalize 4.0.1 with Rails 4.1.1:

```
Category.create(name: 'New Category')
=> NoMethodError: undefined method `reflections' for #<Category::Translation:0x007ff763399330>
```

I have to monkey patch with this code:

``` ruby
module Globalize
  module ActiveRecord
    class Adapter
      protected

      def ensure_foreign_key_for(translation)
        # Sometimes the translation is initialised before a foreign key can be set.
        translation[translation.class.reflections[:globalized_model].foreign_key] = record.id
      end
    end
  end
end
```
