### ISSUE TITLE
attribute_changed? not working on default branch

### ISSUE THREAD

**Issue by basex** [globalize/globalize#607]
```ruby
class Product < ActiveRecord::Base
   translates :name
end

prod = Product.first
prod.name = 'test'
prod.changed? #=> true
prod.changes #=> {"name"=>["old name","test"]}
prod.name_changed? #=> NoMethodError: undefined method `name_changed?' for #<Product:0x007f8343a5af50>
```

This was working in version 5.1.0.beta1 of globalize.
